import Memoji from "@assets/images/memoji.png";

export const DUMMY_ORDER_LIST = [
  {
    orderId: "O001",
    customerName: "John Doe",
    product: "Laptop",
    amount: "$1200",
    orderDate: "2021-08-01",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O002",
    customerName: "Jane Smith",
    product: "Camera",
    amount: "$700",
    orderDate: "2021-08-02",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O003",
    customerName: "Alice Johnson",
    product: "Smartphone",
    amount: "$950",
    orderDate: "2021-08-03",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  {
    orderId: "O004",
    customerName: "Michael Brown",
    product: "Tablet",
    amount: "$550",
    orderDate: "2021-08-04",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  {
    orderId: "O005",
    customerName: "Lucy Blue",
    product: "Monitor",
    amount: "$300",
    orderDate: "2021-08-05",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O006",
    customerName: "Ethan Hunt",
    product: "Keyboard",
    amount: "$150",
    orderDate: "2021-08-06",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O007",
    customerName: "Olivia Green",
    product: "Mouse",
    amount: "$25",
    orderDate: "2021-08-07",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O008",
    customerName: "Noah Lime",
    product: "External Hard Drive",
    amount: "$120",
    orderDate: "2021-08-08",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  {
    orderId: "O009",
    customerName: "Emma Stone",
    product: "Printer",
    amount: "$200",
    orderDate: "2021-08-09",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O010",
    customerName: "Liam Neeson",
    product: "Webcam",
    amount: "$99",
    orderDate: "2021-08-10",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O011",
    customerName: "Sophia Loren",
    product: "Microphone",
    amount: "$80",
    orderDate: "2021-08-11",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  {
    orderId: "O012",
    customerName: "Mason Mount",
    product: "Speaker",
    amount: "$250",
    orderDate: "2021-08-12",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O013",
    customerName: "Isabella River",
    product: "Router",
    amount: "$130",
    orderDate: "2021-08-13",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O014",
    customerName: "Jacob Black",
    product: "SSD",
    amount: "$110",
    orderDate: "2021-08-14",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  // Repeat similar patterns to fill up to 37 orders with creative liberties on products, prices, and dates.
  {
    orderId: "O015",
    customerName: "William Moore",
    product: "Charger",
    amount: "$19",
    orderDate: "2021-08-15",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O016",
    customerName: "James Smith",
    product: "Graphics Card",
    amount: "$399",
    orderDate: "2021-08-16",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O017",
    customerName: "Logan Paul",
    product: "Gaming Console",
    amount: "$499",
    orderDate: "2021-08-17",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  {
    orderId: "O018",
    customerName: "Benjamin Franklin",
    product: "Book",
    amount: "$15",
    orderDate: "2021-08-18",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O019",
    customerName: "Eleanor Rigby",
    product: "Wireless Earphones",
    amount: "$130",
    orderDate: "2021-08-19",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O020",
    customerName: "Oscar Wilde",
    product: "Classic Watch",
    amount: "$250",
    orderDate: "2021-08-20",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O021",
    customerName: "Isaac Newton",
    product: "Scientific Calculator",
    amount: "$20",
    orderDate: "2021-08-21",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  {
    orderId: "O022",
    customerName: "George Orwell",
    product: "Typewriter",
    amount: "$120",
    orderDate: "2021-08-22",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O023",
    customerName: "Jane Austen",
    product: "Book Set",
    amount: "$80",
    orderDate: "2021-08-23",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O024",
    customerName: "Charlie Chaplin",
    product: "Vintage Camera",
    amount: "$350",
    orderDate: "2021-08-24",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  {
    orderId: "O025",
    customerName: "Amelia Earhart",
    product: "Aviator Sunglasses",
    amount: "$90",
    orderDate: "2021-08-25",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O026",
    customerName: "Vincent van Gogh",
    product: "Paint Set",
    amount: "$75",
    orderDate: "2021-08-26",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O027",
    customerName: "Albert Einstein",
    product: "Physics Textbook",
    amount: "$45",
    orderDate: "2021-08-27",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  {
    orderId: "O028",
    customerName: "Frida Kahlo",
    product: "Art Canvas",
    amount: "$50",
    orderDate: "2021-08-28",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O029",
    customerName: "Leonardo da Vinci",
    product: "Sketchbook",
    amount: "$25",
    orderDate: "2021-08-29",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O030",
    customerName: "Pablo Picasso",
    product: "Oil Pastels",
    amount: "$60",
    orderDate: "2021-08-30",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  {
    orderId: "O031",
    customerName: "Ludwig van Beethoven",
    product: "Music Sheets",
    amount: "$40",
    orderDate: "2021-08-31",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O032",
    customerName: "Marilyn Monroe",
    product: "Perfume",
    amount: "$100",
    orderDate: "2021-09-01",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
  {
    orderId: "O033",
    customerName: "Abraham Lincoln",
    product: "History Book",
    amount: "$35",
    orderDate: "2021-09-02",
    shippingStatus: "Delivered",
    profilePhoto: Memoji,
  },
  {
    orderId: "O034",
    customerName: "Cleopatra",
    product: "Gold Necklace",
    amount: "$550",
    orderDate: "2021-09-03",
    shippingStatus: "Processing",
    profilePhoto: Memoji,
  },
  {
    orderId: "O035",
    customerName: "Wolfgang Amadeus Mozart",
    product: "Piano",
    amount: "$1500",
    orderDate: "2021-09-04",
    shippingStatus: "Shipped",
    profilePhoto: Memoji,
  },
];
