import Memoji from "@assets/images/startupfon-purple.jpg";

export const DUMMY_USER_LIST = [
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Finance",
    projectID: "4",
    status: "Tamamlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Yayınlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Arda",
      surname: "Turan",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Finance",
    projectID: "4",
    status: "Tamamlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Yayınlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Arda",
      surname: "Turan",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Finance",
    projectID: "4",
    status: "Tamamlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Yayınlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Arda",
      surname: "Turan",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Finance",
    projectID: "4",
    status: "Tamamlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Yayınlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Arda",
      surname: "Turan",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Finance",
    projectID: "4",
    status: "Tamamlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Yayınlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Arda",
      surname: "Turan",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Finance",
    projectID: "4",
    status: "Tamamlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Ulaş Rotinda",
      surname: "Güler",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Yayınlandı",
    createdAt: "02-02-2020",
  },
  {
    tutar: 100000,
    investorProfile: {
      profilePhoto: Memoji,
      name: "Arda",
      surname: "Turan",
    },
    sektör: "Tech",
    projectID: "2",
    status: "Bekliyor",
    createdAt: "02-02-2020",
  },
];
